name: publish

on:
  push:
    branches:
      - main

env:
  REGISTRY_USERNAME: ${{ secrets.DOCKERHUBUSERNAME }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v3
        if: env.REGISTRY_USERNAME != ''
        with:
          username: ${{ secrets.DOCKERHUBUSERNAME }}
          password: ${{ secrets.DOCKERHUBACCESSTOKEN }}

      - name: Build Docker image
        if: env.REGISTRY_USERNAME != ''
        run: |
          docker build --pull --tag quay.io/terraform-docs/gh-actions:edge .
          docker push ${{ secrets.DOCKERHUBUSERNAME }}/gh-actions:edge

  release-draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
